# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKglbZnzAXTRbvCfMUr8YPAyz0Ux12_a
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Google Play Store Analysis",
    page_icon="📱",
    layout="wide"
)

# -----------------------------
# Custom CSS
# -----------------------------
st.markdown("""
<style>

/* Main Background */
.stApp {
    background: linear-gradient(to right, #f8fbff, #eef5ff);
}

/* Main Title */
h1 {
    color: #1E3A8A;
    text-align: center;
    font-size: 42px !important;
    font-weight: bold;
}

/* Section Headers */
h2, h3 {
    color: #2563EB;
    font-weight: bold;
}

/* Sidebar */
section[data-testid="stSidebar"] {
    background-color: #1E293B;
}

section[data-testid="stSidebar"] * {
    color: white;
}

/* DataFrame */
[data-testid="stDataFrame"] {
    border: 2px solid #2563EB;
    border-radius: 10px;
    overflow: hidden;
}

/* Select Box */
.stSelectbox > div > div {
    border-radius: 10px;
    border: 2px solid #2563EB;
}

/* Metric Cards */
[data-testid="metric-container"] {
    background-color: white;
    border: 1px solid #dbeafe;
    padding: 15px;
    border-radius: 12px;
    box-shadow: 0 3px 10px rgba(0,0,0,0.1);
}

/* Success Box */
.stAlert {
    border-radius: 10px;
}

/* Buttons */
.stButton>button {
    background: linear-gradient(90deg,#2563EB,#3B82F6);
    color: white;
    border: none;
    border-radius: 8px;
    padding: 10px 18px;
    font-weight: bold;
}

.stButton>button:hover {
    background: linear-gradient(90deg,#1D4ED8,#2563EB);
    color: white;
}

</style>
""", unsafe_allow_html=True)

# -----------------------------
# Title
# -----------------------------
st.markdown("""
<h1>📱 Google Play Store App Analysis Dashboard</h1>
<p style="text-align:center;
font-size:18px;
color:gray;">
Analyze Google Play Store apps using interactive charts and insights.
</p>
""", unsafe_allow_html=True)

# -----------------------------
# Load Dataset
# -----------------------------
df = pd.read_csv("googleplaystore_v2.csv")

# -----------------------------
# Dataset
# -----------------------------
st.header("📋 Dataset Preview")
st.dataframe(df, use_container_width=True)

# -----------------------------
# Dataset Information
# -----------------------------
st.header("📑 Dataset Information")

col1, col2 = st.columns(2)

with col1:
    st.metric("📄 Total Rows", f"{df.shape[0]:,}")

with col2:
    st.metric("📊 Total Columns", df.shape[1])

st.subheader("Column Data Types")
st.dataframe(df.dtypes, use_container_width=True)

# -----------------------------
# Data Cleaning
# -----------------------------
st.header("🧹 Data Cleaning")

st.subheader("Missing Values Before Cleaning")
st.dataframe(df.isnull().sum(), use_container_width=True)

# Remove rows with missing Rating
df = df[df["Rating"].notnull()]

# Price
if "Price" in df.columns:
    df["Price"] = (
        df["Price"]
        .astype(str)
        .str.replace("$", "", regex=False)
    )
    df["Price"] = pd.to_numeric(df["Price"], errors="coerce").fillna(0)

# Reviews
if "Reviews" in df.columns:
    df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

# Installs
if "Installs" in df.columns:
    df["Installs"] = (
        df["Installs"]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("+", "", regex=False)
    )
    df["Installs"] = pd.to_numeric(df["Installs"], errors="coerce")

# Size
if "Size" in df.columns:
    df["Size"] = (
        df["Size"]
        .astype(str)
        .str.replace("M", "", regex=False)
        .str.replace("k", "", regex=False)
    )

st.subheader("Missing Values After Cleaning")
st.dataframe(df.isnull().sum(), use_container_width=True)

st.success("✅ Data Cleaning Completed Successfully")

# -----------------------------
# Visualizations
# -----------------------------
st.header("📊 Interactive Visualizations")

chart = st.selectbox(
    "Select a Chart",
    (
        "Rating Distribution",
        "Price Distribution",
        "Content Rating",
        "Top Categories",
        "Rating vs Reviews"
    )
)

with st.container(border=True):

    if chart == "Rating Distribution":

        fig, ax = plt.subplots(figsize=(8,5))
        sns.histplot(
            df["Rating"],
            bins=20,
            kde=True,
            color="royalblue",
            ax=ax
        )
        ax.set_title("Rating Distribution")
        ax.set_xlabel("Rating")
        ax.set_ylabel("Count")
        st.pyplot(fig)

    elif chart == "Price Distribution":

        fig, ax = plt.subplots(figsize=(8,5))
        sns.histplot(
            df["Price"],
            bins=20,
            color="green",
            ax=ax
        )
        ax.set_title("Price Distribution")
        ax.set_xlabel("Price ($)")
        st.pyplot(fig)

    elif chart == "Content Rating":

        fig, ax = plt.subplots(figsize=(8,5))
        df["Content Rating"].value_counts().plot(
            kind="bar",
            color="orange",
            ax=ax
        )
        ax.set_title("Content Rating")
        ax.set_ylabel("Number of Apps")
        st.pyplot(fig)

    elif chart == "Top Categories":

        fig, ax = plt.subplots(figsize=(10,5))
        df["Category"].value_counts().head(10).plot(
            kind="bar",
            color="purple",
            ax=ax
        )
        ax.set_title("Top 10 Categories")
        ax.set_ylabel("Number of Apps")
        st.pyplot(fig)

    elif chart == "Rating vs Reviews":

        fig, ax = plt.subplots(figsize=(8,5))
        sns.scatterplot(
            data=df,
            x="Reviews",
            y="Rating",
            color="red",
            ax=ax
        )
        ax.set_title("Rating vs Reviews")
        st.pyplot(fig)

# -----------------------------
# Summary Statistics
# -----------------------------
st.header("📈 Summary Statistics")

st.dataframe(df.describe(), use_container_width=True)

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")

st.markdown("""
<div style="text-align:center;
font-size:16px;
color:gray;
padding:15px;">
❤️ Developed using <b>Streamlit</b> | Google Play Store Analysis Dashboard
</div>
""", unsafe_allow_html=True)
