# -*- coding: utf-8 -*-
"""project4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxuLjx08gBG_8Z-ykrngsmYHTGZO4jXq
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

st.set_page_config(page_title="Employee Retention Prediction", layout="wide")

st.title("Employee Retention Prediction using Logistic Regression")

uploaded_file = st.file_uploader("Upload HR_comma_sep.csv", type=["csv"])

if uploaded_file is not None:

    df = pd.read_csv(uploaded_file)

    st.subheader("Dataset")
    st.dataframe(df.head())

    left = df[df["left"] == 1]
    retained = df[df["left"] == 0]

    col1, col2 = st.columns(2)

    with col1:
        st.metric("Employees Left", left.shape[0])

    with col2:
        st.metric("Employees Retained", retained.shape[0])

    st.subheader("Average Values Grouped by Left")

    avg = df.groupby("left")[[
        "satisfaction_level",
        "last_evaluation",
        "number_project",
        "average_montly_hours",
        "time_spend_company"
    ]].mean()

    st.dataframe(avg)

    # Salary chart
    st.subheader("Salary vs Employee Retention")

    fig1, ax1 = plt.subplots(figsize=(6, 4))
    pd.crosstab(df["salary"], df["left"]).plot(kind="bar", ax=ax1)
    st.pyplot(fig1)

    # Department chart
    st.subheader("Department vs Employee Retention")

    fig2, ax2 = plt.subplots(figsize=(10, 5))

    # Handles both 'Department' and 'department'
    dept_col = "Department" if "Department" in df.columns else "department"

    pd.crosstab(df[dept_col], df["left"]).plot(kind="bar", ax=ax2)
    st.pyplot(fig2)

    # Feature Selection
    subdf = df[[
        "satisfaction_level",
        "average_montly_hours",
        "promotion_last_5years",
        "salary"
    ]]

    salary_dummies = pd.get_dummies(subdf["salary"], prefix="salary")

    X = pd.concat(
        [
            subdf.drop("salary", axis=1),
            salary_dummies
        ],
        axis=1
    )

    y = df["left"]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.30,
        random_state=42
    )

    model = LogisticRegression(max_iter=1000)

    model.fit(X_train, y_train)

    accuracy = model.score(X_test, y_test)

    st.subheader("Model Accuracy")
    st.success(f"{accuracy*100:.2f}%")

    st.subheader("Predict Employee Retention")

    satisfaction = st.slider(
        "Satisfaction Level",
        0.0,
        1.0,
        0.5
    )

    monthly_hours = st.slider(
        "Average Monthly Hours",
        80,
        350,
        200
    )

    promotion = st.selectbox(
        "Promotion in Last 5 Years",
        [0, 1]
    )

    salary = st.selectbox(
        "Salary",
        ["low", "medium", "high"]
    )

    input_df = pd.DataFrame({
        "satisfaction_level": [satisfaction],
        "average_montly_hours": [monthly_hours],
        "promotion_last_5years": [promotion],
        "salary_high": [1 if salary == "high" else 0],
        "salary_low": [1 if salary == "low" else 0],
        "salary_medium": [1 if salary == "medium" else 0]
    })

    # Ensure same column order as training data
    input_df = input_df.reindex(columns=X.columns, fill_value=0)

    if st.button("Predict"):

        prediction = model.predict(input_df)[0]
        probability = model.predict_proba(input_df)[0]

        if prediction == 1:
            st.error("Employee is likely to leave.")
        else:
            st.success("Employee is likely to stay.")

        st.write(f"Probability of Staying: {probability[0]:.2%}")
        st.write(f"Probability of Leaving: {probability[1]:.2%}")

else:
    st.info("Please upload HR_comma_sep.csv")
   
