# -*- coding: utf-8 -*-
"""project 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19HX_dji8EAJ-CE0c1Wj-3xnqTdZL3qJB
"""

import streamlit as st
import pandas as pd

# Title
st.title("Airbnb NYC Price Outlier Removal")

# Upload CSV file
uploaded_file = st.file_uploader("Upload AB_NYC_2019.csv", type=["csv"])

if uploaded_file is not None:
    # Read data
    df = pd.read_csv(uploaded_file)

    st.subheader("Original Dataset")
    st.write(df.head())

    st.subheader("Price Statistics (Before Removing Outliers)")
    st.write(df["price"].describe())

    # Calculate thresholds
    min_threshold, max_threshold = df["price"].quantile([0.01, 0.999])

    st.write(f"**Minimum Threshold (1%):** {min_threshold}")
    st.write(f"**Maximum Threshold (99.9%):** {max_threshold}")

    # Display outliers
    st.subheader("Rows Below Minimum Threshold")
    st.write(df[df["price"] < min_threshold])

    # Remove outliers
    df2 = df[(df["price"] > min_threshold) & (df["price"] < max_threshold)]

    st.subheader("Dataset After Removing Outliers")
    st.write(f"Shape: {df2.shape}")

    st.subheader("Random 5 Samples")
    st.write(df2.sample(5))

    st.subheader("Price Statistics (After Removing Outliers)")
    st.write(df2["price"].describe())

    # Download cleaned dataset
    csv = df2.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="Download Cleaned Dataset",
        data=csv,
        file_name="AB_NYC_2019_cleaned.csv",
        mime="text/csv"
    )

else:
    st.info("Please upload the AB_NYC_2019.csv file.")
