# -*- coding: utf-8 -*-
"""Project 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4Ejhy0Nt8wDBAJhzOtXdPBUzYeSsETO
"""
import streamlit as st
import numpy as np
from PIL import Image
import os

# Try importing TensorFlow
try:
    import tensorflow as tf
except ModuleNotFoundError:
    st.error("TensorFlow is not installed. Please check requirements.txt and the deployment environment.")
    st.stop()

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Male & Female Eye Classifier",
    page_icon="👁️",
    layout="centered"
)

# -----------------------------
# Load Model
# -----------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "eye_gender_classifier.keras")

if not os.path.exists(MODEL_PATH):
    st.error(f"Model file not found:\n{MODEL_PATH}")
    st.stop()

try:
    model = tf.keras.models.load_model(MODEL_PATH)
except Exception as e:
    st.error(f"Unable to load model:\n{e}")
    st.stop()

# -----------------------------
# Title
# -----------------------------
st.title("👁️ Male & Female Eye Classifier")

st.write("Upload an eye image to predict Male or Female.")

uploaded_file = st.file_uploader(
    "Choose an Eye Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file:

    image = Image.open(uploaded_file).convert("RGB")

    st.image(image, caption="Uploaded Image", use_container_width=True)

    img = image.resize((128,128))

    img = np.array(img).astype("float32") / 255.0

    img = np.expand_dims(img, axis=0)

    prediction = model.predict(img, verbose=0)[0][0]

    if prediction >= 0.5:
        st.success(f"👨 Male Eye\n\nConfidence: {prediction*100:.2f}%")
    else:
        st.success(f"👩 Female Eye\n\nConfidence: {(1-prediction)*100:.2f}%")

