# -*- coding: utf-8 -*-
"""Project 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4Ejhy0Nt8wDBAJhzOtXdPBUzYeSsETO
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import os

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Male & Female Eye Classifier",
    page_icon="👁️",
    layout="centered"
)

# -----------------------------
# Load Model
# -----------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "eye_gender_classifier.keras")

model = tf.keras.models.load_model(MODEL_PATH)

# -----------------------------
# Title
# -----------------------------
st.title("👁️ Male & Female Eye Classifier")

st.write(
    "Upload an eye image and the model will predict whether it belongs to a Male or Female."
)

# -----------------------------
# Upload Image
# -----------------------------
uploaded_file = st.file_uploader(
    "Choose an Eye Image",
    type=["jpg", "jpeg", "png"]
)

# -----------------------------
# Prediction
# -----------------------------
if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    st.image(image, caption="Uploaded Image", use_container_width=True)

    img = image.resize((128, 128))

    img_array = np.array(img)

    img_array = img_array / 255.0

    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)[0][0]

    st.write("### Prediction Result")

    if prediction >= 0.5:
        st.success("👨 Male Eye")
        st.write(f"Confidence : {prediction*100:.2f}%")
    else:
        st.success("👩 Female Eye")
        st.write(f"Confidence : {(1-prediction)*100:.2f}%")

